---
# tasks file for install_nextcloud

- name: Create deployment directory
  file:
    path: /root/deployment
    state: directory

- name: Generate .env file
  template:
    src: /root/ansible-Nextcloud/template.env.j2
    dest: /root/deployment/.env

- name: Create docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /root/deployment/docker-compose.yml

- name: Create traefik network
  docker_network:
    name: traefik
    state: present

- name: Copy Traefik configuration files
  copy:
    src: /root/ansible-Nextcloud/traefik
    dest: /root/deployment

- name: Generate .env file for traefik
  template:
    src: /root/ansible-Nextcloud/template_traefik.env.j2
    dest: /root/deployment/traefik/.env

- name: Create traefik file from template
  template:
    src: traefik.yml.j2
    dest: /root/deployment/traefik/traefik.yml

- name: Restart Docker service
  systemd:
    name: docker
    state: restarted

- name: Run docker compose up
  command: "docker compose up -d"
  args:
    chdir: /root/deployment/traefik

# - name: Set permissions for acme.json
#   command: chmod 600 /root/deployment/traefik/acme.json


