---
- hosts: testuser   # The group name from your hosts.ini file, can also just be the IP
  become: yes
  vars_files:
    - vars.yml #gebruik de centrale vars.yml bestand
  roles:
    # - role: update_system_packages
    # - role: uninstall_nginx
    - role: change_hostname
    - role: set_static_ip
    - role: install_docker
    - role: install_nextcloud
    - role: firewall_role
    - role: traefik_requirements
