---
# tasks file for install_docker

- name: Update package cache and install necessary packages
  package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker GPG key
  shell: curl -fsSL https://download.docker.com/linux/rhel/gpg | sudo gpg --import -

- name: Add Docker repository
  shell: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker packages
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Install setuptools-rust
  pip:
    name: setuptools-rust
    state: present

# - name: Install Docker Compose
#   pip:
#     name: docker compose
#     state: present
