---
# tasks file for firewall_role

- name: Allow HTTP (port 80) and HTTPS (port 443) traffic
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  loop:
    - 80
    - 443
  become: true

