---
# tasks file for firewall_role

- name: Stop Firewalld service
  service:
    name: firewalld
    state: stopped

- name: Disable Firewalld service on boot
  service:
    name: firewalld
    enabled: no

- name: Allow HTTP (port 80) and HTTPS (port 443) traffic
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  loop:
    - 80
    - 443
    - 3306
  become: true

